### PR TITLE
Add support for webhooks

### PR DESCRIPTION
**Pull request by BenoitMercier**
Added support for webhooks. See webhooks.md for details.

### CODE REVIEW

**Comment by jimboca** [comment]
@BenoitMercier is there a way this can be made to work on the local network? I have NS's where I have a simple REST server, but would prefer to use something like this but not go thru portal.

**Comment by BenoitMercier** [comment]
> @BenoitMercier is there a way this can be made to work on the local network? I have NS's where I have a simple REST server, but would prefer to use something like this but not go thru portal.

This would have to be implemented in PG3 itself. 

When local, a web server integrated in the nodeserver is a good option.

**Comment by jimboca** [comment]
Thanks, just would be nice to have a standard way to handle thru PG3, I've been discussing this with Bob eariler today.

**Comment by BenoitMercier** [comment]
> Thanks, just would be nice to have a standard way to handle thru PG3, I've been discussing this with Bob eariler today.

If Bob wants to, I could help get the API in PG3. It just needs to do the same: Capture the body, query & headers, send it to a topic, listen to responses and return the response.

**Comment by bpaauwe** [comment]
A couple of general comments

1. All of the white space changes makes it hard to review the actual feature changes.  I'd prefer to see white space changes as a separate commit, FYi.
2. Does this actually work?  I don't see it subscribing to any new topics. The existing topic that the the interface listens to is suppose to only be writable by PG3 or ISY.   I really hope we aren't overriding/bypassing all of the local MQTT security when we connect to the IOT bridge.

Otherwise, the implementation looks ok.

**Comment by bpaauwe** [comment]
I didn't see the comments about PG3 until after I sent the previous one, but maybe that's a better solution overall,  If PG3 sends the webhook to the interface it can get the data either from the portal (via MQTT bridge) or local from it's own web server.

Based on the slack discussion, I'm assuming that @jimboca has something on the local network that he wants to send data to the node server via an http request, not something that's  on a remote network.

**Comment by BenoitMercier** [comment]
> A couple of general comments
> 
> 1. All of the white space changes makes it hard to review the actual feature changes.  I'd prefer to see white space changes as a separate commit, FYi.
> 2. Does this actually work?  I don't see it subscribing to any new topics. The existing topic that the the interface listens to is suppose to only be writable by PG3 or ISY.   I really hope we aren't overriding/bypassing all of the local MQTT security when we connect to the IOT bridge.
> 
> Otherwise, the implementation looks ok.

Sorry for the whitespaces. 

Yes it does work. There are 2 files that need to be updated on eisy to work though. Will be on the next release, I sent it to Michel.

The inbound topic is udi/pg3/ns/clients/#, the same it currently listens to.
The outbound topic is new: udi/pg3/ns/portal/<uuid>_<slot>

You need not to worry about the security when it comes to IoT Core. I made it pretty tight.
The mosquitto bridge now subscribes to udi/pg3/ns/clients/#, and only portal is allowed to publish to that topic. 
The mosquitto bridge also allows to udi/pg3/ns/portal/#, and only portal is allowed to subscribe to it.

Benoit

**Comment by bpaauwe** [comment]
@BenoitMercier Not that I don't trust you to make it secure, I do.  But it seems like we've gone to all the trouble to minimize the attack surface with the local broker config, but are now creating a much larger attack surface by allowing essentially unlimited input from an external source.

If I add the ability to send webhook messages from PG3 to the node server, is there any advantage to routing the portal messages through PG3 instead of direct to the node server?

The only advantage I can think of right now is that it would simplify the code in the interface a bit.  It would just need to send a response back to PG3 and PG3 would then need to determine where to route that response. Otherwise, we'll need a way in the interface to tell where the message came from so it then knows what topic to publish the response on.

**Comment by BenoitMercier** [comment]
@bpaauwe 
Routing through PG3: 
+ Can enforce the format of the messages

Routing directly:
+ Performance as we don't have PG3 in the way (I'm thinking webhooks might be used at a high rate)
+ Less moving parts. When it don't communicate it can be the NS, the interface, Mosquitto config, eisy IoT rules, Portal IoT rule... it's already many things to check. 

My preference is definitely direct.
In terms of security, to me it's equivalent as PG3 would not have any specific logic to block calls, it would relay everything.

We can rename the response topic to something else. But I would make it a dedicated topic as the clients don't need to listen to that.

**Comment by bpaauwe** [comment]
Good reasons for direct. But here's my thoughts.  If we want basically the same thing for local (which is what @jimboca and I were already discussing), I'm not sure it makes sense to have to almost identical events in the interface; webhooks1 that gets and responds to portal and webhooks2 that gets and responds to PG3.

We could extend what you have here a bit so that the incoming message includes the information about where the message is coming from (portal or PG3).  Then use that to direct the response.  Which is better.

If it routes through PG3, then PG3 needs the logic to know where to respond, to the portal or directly to the http request. With the added complexities.

I think what bothers me is that the communication between the node server and PG3 was a private interface on a private MQTT topic.  Allowing something not PG3 to also make use of it seems somehow wrong.  I want to make sure we understand the implications because

a) if it's no longer private, it should be documented and versioned.
b) what does it mean to allow non-PG3 entities to send messages to the node server?
c) does now need to have something in the message to identify the sender so the node server can determine if it's legit or not?
d) this does impact the node.js interface as well.
e) this locks us into using MQTT as the protocol.  I've had thoughts of replacing the MQTT protocol between PG3 and NS as I don't think it's really the right protocol for what we do, but if we allow portal to use it too, that becomes virtually impossible.

Polyglot was designed to be the proxy between the node server code and ISY, if we're not going to use it between the node server and portal, then should we be using it at all?

**Comment by BenoitMercier** [comment]
> Good reasons for direct. But here's my thoughts. If we want basically the same thing for local (which is what @jimboca and I were already discussing), I'm not sure it makes sense to have to almost identical events in the interface; webhooks1 that gets and responds to portal and webhooks2 that gets and responds to PG3.
> 
> We could extend what you have here a bit so that the incoming message includes the information about where the message is coming from (portal or PG3). Then use that to direct the response. Which is better.
> 
> If it routes through PG3, then PG3 needs the logic to know where to respond, to the portal or directly to the http request. With the added complexities.

Not necessarily. Both portal and PG3 can listen to a topic, and act on it if it's for them. Just like several clients can be active and listen to responses, and act if it's for them.

> I think what bothers me is that the communication between the node server and PG3 was a private interface on a private MQTT topic. Allowing something not PG3 to also make use of it seems somehow wrong. I want to make sure we understand the implications because
> 
> a) if it's no longer private, it should be documented and versioned. b) what does it mean to allow non-PG3 entities to send messages to the node server? c) does now need to have something in the message to identify the sender so the node server can determine if it's legit or not? d) this does impact the node.js interface as well. e) this locks us into using MQTT as the protocol. I've had thoughts of replacing the MQTT protocol between PG3 and NS as I don't think it's really the right protocol for what we do, but if we allow portal to use it too, that becomes virtually impossible.
> 
> Polyglot was designed to be the proxy between the node server code and ISY, if we're not going to use it between the node server and portal, then should we be using it at all?

I don't mind going through PG3.
Just let me know what topic to write to and get responses from. I'll take care of the bridge, IoT config and portal.

Benoit

**Review by bpaauwe — APPROVED** [review]

**Pull request merged**
