### PR TITLE
Driver restore

### PR DESCRIPTION
**Pull request by jimboca**
Bob,

I think this is a better option, and creates less traffic!  By default it does not restore values to the previous ones stored in the database since typically on startup the node server will set values as appropriate.  But, when we have user settable values we want those restored.  To make this work you can now set the parameter on the driver:

```
        {'driver': 'GV7', 'value': 0, 'uom': 2,  'restore':True},
```

The only issue will be for nodeservers that currently rely on this, they will need to be updated.  Alternative is to assume True, but I'd rather not.

This is just a proposal, and I confirmed it works using my ELK NS.

- Jim

### CODE REVIEW

**Comment by jimboca** [comment]
weird, I thought I created the new branch off the master so I'm not sure why it's mentioning changes from my jimbo branch... Just when I think I understand git it does something I don't understand...

**Comment by bpaauwe** [comment]
I don't see how this would reduce the traffic or really have much of an impact at all.  If it does, that may indicate that there's a bug someplace else.

The way things should be working is:

A node class has a class variable called drivers.  The drivers object contains the driver name ('ST') the driver UOM and the driver default value.

1. the node server creates a node object
2. during the node object initialization, it check the database for saved driver values
3. if saved driver values are found, the default value for the driver is updated.
4. the node server does an addnode() to add this new node to the ISY and the PG3 database
5. if the node doesn't exist on the ISY, it is added to the ISY
6. it then pushes the driver default values to the ISY

Your change only effects step 3 which defines what the default value for each driver is.

**Comment by jimboca** [comment]
As I mentioned on the slack, this is to try and solve the issue where the old value from 3. is overriding the newly set value when the nodeserver starts up.  I thought you understood why that is happening. I don't know the intricacies of the code as well as you but this seemed like a good solution to resolve it.  My main problem right now is that the node specified as conn_status is not always getting set correctly because the old value from 3 or maybe 6 is clobbering it.  Seems like a driver_restore setting resolves this, but if you have a better solution I'm all for it.  We could also add a set_default value as well to tell it never even set 6 on startup because the node server will take care of it, or just allow not specifying a default?  
The reason I said less traffic is that if the node server knows that 3 and 6 are not required, then don't even send it because the real value will be coming later.  When PG is restarted it creates a ton of traffic, so just thinking of ways to help with that, and resolve my real issue as well.

**Comment by bpaauwe** [comment]
Yes, I realized you were trying to solve that problem, but this change shouldn't make any difference.  If it does, then it's just because the code changed, it changed the timing of the race condition and you got lucky.

The only difference your patch makes is what value is pushed in step 6, since that is happening within the PG3 code, nothing you do in the interface will change that.

Polyglot seems to have been designed from day 1 to have a race condition issue with addnode().  We've worked around the normal case with the ADDNODEDONE event so that the node server can wait and not race with it.  But the connection status is internal to PG3 and that can still race with the addnode.  There's not really anything the node server or interface can do about this case, it's all internal to PG3.

There are a couple of solutions.  One would be to rip out all the queuing code and replace it with something that allows 'fencing' or tracking jobs in the queue so that you can link one job in the queue to another such that the second won't start until the first is finished.  That probably ups the complexity of the PG3 code base by 2 or 3x.  It's very difficult to get right. I use to work on this type of code for graphics drivers.  Very few people actually understood that code well and it was under constant change trying to get it working right.

The second would be to add some type of locking mechanism to node operations.  But because PG3 doesn't just have 1 copy of the node data structure; each message being processed could be using it's own copy of the data structure.  Adding locking that would work with this design isn't going to be simple either. I'm not even sure if node.js really supports locking or if we'd then end up with deadlocks all over the place.

I'll have to think about it some to see if I can come up with a way to work around this one case.  But this is something that will need to be addressed in PG4.

**Comment by jimboca** [comment]
I don't understand, if step 6 value is never passed where is the race?

**Comment by bpaauwe** [comment]
I edited step 6 to take out the word 'default'

step 6 always happens and drivers always have a value associated with them.  I initial said default, because addnode is using the value in the driver array vs. a value passed in.  The value is either the value set in the static initialization of the driver array or the value after it was updated from the database. 

If I understand your change correctly, it just disables updating the value from the database.  Thus the value will always then be the value set in the static initialization.

**Comment by jimboca** [comment]
With this commit you added the new code to restore driver default values:
https://github.com/UniversalDevicesInc/udi_python_interface/commit/d3d6ee0244c2e8c4927ce4ce6dbc1c0ca00fc27b
Which my change allows skipping that setting of the default obtained from db_getNodeDrivers, and I'm also suggesting allowing the default value in drivers array to be left out so it will never try to set the initial value.
I understand this is a race due to the design of PG, but just trying to get something to help stop users complaining that values are incorrect.
If you still don't agree then I'll give up and close this and just go back to complaining about it instead of trying to help and direct all user complaints your way.

**Comment by bpaauwe** [comment]
> With this commit you added the new code to restore driver default values: [d3d6ee0](https://github.com/UniversalDevicesInc/udi_python_interface/commit/d3d6ee0244c2e8c4927ce4ce6dbc1c0ca00fc27b) Which my change allows skipping that setting of the default obtained from db_getNodeDrivers, and I'm also suggesting allowing the default value in drivers array to be left out so it will never try to set the initial value. 

This is the first you've mentioned "I'm also suggesting allowing the default value in drivers array to be left out so it will never try to set the initial value". That isn't part of the commit or the commit message.   And I still don't understand what this commit has to do with this issue.  As I said initially, if this changed the behavior for you, it is only because you changed the timing such that the race now ends the way you want.  At least until something else switches the timing back. It's not a solution or even a partial solution.

If you believe your commit actually solves or partially solves the problem, then you need to better explain it to me, because I'm not seeing that. 

And I'm not trying to discourage you from suggesting fixes/improvements, just the opposite in fact.  If I didn't think your input was valuable, I'd just reject this and not spend all this time trying to explain why I think it doesn't work and what I believe is happening in the code. 

I still think the right solution is to have addnode block but I'm not sure how to do that as the whole design of PG3 is based around the idea that it shouldn't ever block.

PG3 message handling is racy by design.  It just that in a majority of the cases, it is very unlikely to cause problems. addnode() is the one case where it becomes a lot more likely. So how do we reduce the impact of this one case without adversely effecting all the other cases?

**Comment by jimboca** [comment]
No I had said this before:

>> My main problem right now is that the node specified as conn_status is not always getting set correctly because the old value from 3 or maybe 6 is clobbering it. Seems like a driver_restore setting resolves this, but if you have a better solution I'm all for it. We could also add a set_default value as well to tell it never even set 6 on startup because the node server will take care of it, **or just allow not specifying a default?**

So I was hoping to gain more reliable setting of proper values since the defaults should never be taken, and ignore previous stored values which doing both will reduce startup traffic which pounds my ISY.  Allowing a NS to say don't ever set the default because I'll be setting it later (or PG will set it later for conn_status, which should never get a default or previous value) seems like a pretty simple explanation.  

For some nodes the NS knows the correct value on startup, so I suppose those could modify the drivers array inside__init__  which would help as well, but that's not always the case.

As I said, I realize the right solution is a better PG design, but that won't happen for a long time and users (especially those using ELK NS) get a little freaked out when the NS says it's Disconnected, when it's really not.  Mine actually says that right now because PG3 just restarted about an hour ago for some reason.  It is discouraging when a solution is proposed, which is pretty simple and worked for me with many restarts, but it's dismissed because the better solution is way out in the future.

This can be done in a way to not cause any adverse affects by keeping current defaults and force setting it where desired.

**Comment by bpaauwe** [comment]
I'm pretty sure we want the same thing.  Let's see if I can draw a picture of what I believe is happening and why I think this commit doesn't solve the problem.
image_2022-04-13_141630
**timing is not to any kind of scale and size of box doesn't represent the relative amount of time each operation takes.**

The problem is that any setDriver calls for the controller node between points A and B are likely to be overwritten when addnode updates the ISY.  It doesn't matter if those setDriver calls are made by the node server or internally in PG3.   So if the connection status is updated between those two points, it gets overwritten.

Right now, the connection status and addnode boxes represent independent, asynchronous tasks.  

This commit changes code in very first box labeled "initialize Node".   So while that probably effects the timing and that change in timing is maybe enough to move the connection status beyond point B, it isn't a solution as another change in either the interface, your node server or PG3 could just as easily move it back.

If we don't do the update ISY drivers as part of addnode, we'd not have this problem.  And while you may be OK with that change in behavior, that doesn't mean that other node servers aren't relying on the current behavior.

Maybe we have addnode check if the node/driver is the connection status node/driver and skip the ISY update for just that node/driver?  I don't like the idea of making addnode take more time but this specific node/driver is special and maybe it's worth the extra processing time to add special handling.  The only problem I see with this is that addnode has to be called first before we can flag the node/driver as being used for connection status. But I think this problem exists today too.

**Comment by jimboca** [comment]
Thanks, the picture helps.

>> If we don't do the update ISY drivers as part of addnode, we'd not have this problem. And while you may be OK with that change in behavior, that doesn't mean that other node servers aren't relying on the current behavior.

That's why I proposed it could be optional, but I'd prefer it be default behavior and we  notify all developers of a potential change.  If the proposed method completely avoids this race condition then I think it may be accepted.

>> Maybe we have addnode check if the node/driver is the connection status node/driver and skip the ISY update for just that node/driver?

Yes, if we can't change the behavior that will fix my current real issue.  All others seem to be fixed by moving more to addnodedone.

I just had to re-work another nodeserver to wait on doing the "discover" until the addnodedone was called for the controller.  Not sure what has changed but seems to be a bigger problem and probably should let everyone know before they pull their hair out like I have done.  I apologize for getting grumpy, it just didn't feel like I was getting anywhere and didn't understand and I've spent more time fighting this issue lately taking away from time to make real fixes/improvements to my node servers when I do have some free time.

I still feel like not sending any default values at all is the best to avoid traffic on PG restart, and if node servers want that a new method can be provided.

**Pull request closed without merging**
